SELECT CUSTOMER.*,
    CASE
        WHEN TRUNC(MONTHS_BETWEEN(SYSDATE, ENROLL_DT) / 12) >= 10 THEN '10년 이상'
        WHEN TRUNC(MONTHS_BETWEEN(SYSDATE, ENROLL_DT) / 12) >= 5 THEN '5년 이상'
        ELSE '5년 이하'
    END AS 년도수
FROM CUSTOMER
ORDER BY 년도수;