select * from tab;

CREATE VIEW VW_SIMPLE
AS SELECT EMP.EMPNO,EMP.ENAME,DEPT.DNAME,SALGRADE.GRADE AS GD
FROM EMP, DEPT, SALGRADE
WHERE EMP.DEPTNO = DEPT.DEPTNO AND 
EMP.SAL BETWEEN SALGRADE.LOSAL AND SALGRADE.HISAL;

desc vw_simple

select * from tab;
select * from vw_simple; 

CREATE TABLE DBA_TBLS
AS SELECT OWNER, TABLE_NAME FROM DBA_TABLES;

SELECT * FROM DBA_TBLS;
SELECT OWNER,COUNT(*)
FROM DBA_TBLS
GROUP BY OWNER;

CREATE OR REPLACE VIEW VW_DIFF
AS SELECT * FROM DBA_TBLS WHERE OWNER = USER;

SELECT * FROM VW_DIFF;
SELECT COUNT(*) FROM VW_DIFF;

