select DEPTNO, SAL,
round(sum(SAL)/e.sum_sal*100,2)||'%' as sal_rate
from emp, (select sum(SAL) as sum_sal from emp) e;

SELECT DEPTNO, SAL,
ROUND(SAL/e.sum_sal*100,2)||'%' AS SAL_RATE
FROM EMP, (SELECT SUM(SAL) AS sum_sal FROM EMP)e;

select * from emp;

SELECT DEPTNO,SAL,
ROUND(SAL/e.sum_sal*100,2)||'%' AS SAL_RATE
FROM EMP, (SELECT SUM(SAL) AS sum_sal FROM EMP)e;

SELECT DEPTNO, SAL,
ROUND((RATIO_TO_REPORT(SAL) OVER())*100,2) AS SAL_RATE
FROM EMP;

SELECT DEPTNO, SAL,
ROUND((RATIO_TO_REPORT(SAL) OVER())*100,2) AS SAL_RATE
FROM EMP;

SELECT DEPTNO, SAL,
ROUND(SAL/e.sum_sal*100,2)||'%' AS sum_sal
FROM EMP, (SELECT SUM(SAL) AS sum_sal FROM EMP)e;

SELECT DEPTNO,SAL,
ROUND((RATIO_TO_REPORT(SAL)OVER())*100,2)AS SAL_RATE
FROM EMP;

CREATE SEQUENCE WAITING_SEQ3
    START WITH 1
    INCREMENT BY 1
    MAXVALUE   10
    MINVALUE   1
    CYCLE
    CACHE   9
;

CREATE SEQUENCE WAITING_ORDER
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10
    CYCLE
    CACHE    9
;
SELECT WAITING_ORDER.NEXTVAL FROM DUAL;
SELECT to_char(WAITING_ORDER.NEXTVAL,'000000')AS 접수번호 FROM DUAL;
SELECT WAITING_SEQ3.NEXTVAL FROM DUAL;
SELECT WAITING_SEQ3.CURRVAL FROM DUAL;
