CREATE VIEW VW_EMP(ENO,E_NAME,DNO,SAL) 
AS SELECT EMPNO,ENAME,DEPTNO,SAL 
FROM EMP 
WHERE SAL > 1500; 

CREATE TABLE DBA_TBLS
AS SELECT OWNER, TABLE_NAME FROM DBA_TABLES;

SELECT * FROM DBA_TBLS;
SELECT OWNER,COUNT(*)
FROM DBA_TBLS
GROUP BY OWNER;

CREATE OR REPLACE VIEW VW_DIFF
AS SELECT * FROM DBA_TBLS WHERE OWNER = USER;

SELECT * FROM VW_DIFF;
SELECT COUNT(*) FROM VW_DIFF;