SELECT * FROM EMP WHERE SAL = '3000';

SELECT ROWNUM, ENAME, DEPTNO, SAL FROM EMP ORDER BY DEPTNO, SAL;

SELECT ROWNUM, ENAME, DEPTNO, SAl FROM EMP WHERE DEPTNO IN (10,20) ORDER BY DEPTNO, SAL;

SELECT ENAME, DEPTNO, SAL FROM EMP WHERE ROWNUM = 1;
SELECT ENAME, DEPTNO, SAL FROm EMP WHERE ROWNUM = 3;
SELECT ENAME, DEPTNO, SAL FROm EMP WHERE ROWNUM > 3;
SELECT ENAME, DEPTNO, SAL FROM EMP WHERE ROWNUM <= 3;
SELECT ENAME, DEPTNO, SAL FROM EMP WHERE ROWNUM < 3;

SELECT sysdate FROM dual;

desc v$mystat
select sid from v$mystat;

ALTER SESSION SET NLS_DATE_FORMAT = 'RR-MON-RR';

SELECT NEXT_DAY((LAST_DAY(SYSDATE)-7),6) FROM DUAL;

SELECT DEPTNO, MIN(SAL), MAX(SAL) FROM SCOTT.EMP GROUP BY DEPTNO;
SELECT NEXT_DAY((LAST_DAY(SYSTATE)-7),6) FROM DUAL;


INSERT INTO DEPT(DEPTNO,DNAME,LOC) VALUES(90,'신사업부','경기도');
UPDATE EMP SET DEPTNO = 90 WHERE DEPTNO = 30;
DELETE FROM DEPT WHERE DEPTNO = 30;
SELECT * FROM DEPT;
SELECT * FROM EMP WHERE DEPTNO = 30;
ROLLBACK;
SELECT * FROM DEPT; 
SELECT * FROM EMP;

INSERT INTO EMP(EMPNO, ENAME, JOB, SAL) VALUES(1111,'ORACLE','DBA',3500);
SELECT * FROM EMP;
UPDATE EMP SET SAL = SAL * 1.3 WHERE EMPNO = 1111;
COMMIT;
ROLLBACK;
SELECT * FROM EMP;

ROLLBACK;
DELETE FROM EMP WHERE EMPNO = 1111;
ROLLBACK;

DESC EMP;
ROLLBACK;
DELETE FROM EMP WHERE EMPNO = 1111;
UPDATE EMP SET SAL = 12345678 WHERE EMPNO = 7788;
UPDATE EMP SET SAL = 1234 WHERE EMPTNO = 7902;
COMMIT;
SELECT EMPNO, SAL FROM EMP WHERE EMPNO IN (1111,7788,7902);

BEGIN
    DELETE FROM EMP WHERE DEPTNO = 20;
    UPDATE EMP SET SAL = 123456789 WHERE EMPNO = 7499;
    UPDATE EMP SET SAL = 1234 WHERE EMPNO = 7698;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END;

SELECT EMPNO, SAL FROM EMP WHERE DEPTNO = 20 or EMPNO IN (7499,7698);