
TRUNCATE TABLE BONUS;
SET SERVEROUTPUT ON
DECLARE
    CUR_VAR     SYS_REFCURSOR;
    R_CUR_EMP   EMP%ROWTYPE;
    V_SQL       VARCHAR2(200);
BEGIN
    V_SQL := 'SELECT ENAME,JOB,SAL,COMM FROM EMP WHERE DEPTNO =:V_DEPTNO';
    OPEN CUR_VAR FOR V_SQL USING 10;
    LOOP
        FETCH CUR_VAR INTO 
                    R_CUR_EMP.ENAME,R_CUR_EMP.JOB,R_CUR_EMP.SAL,R_CUR_EMP.COMM;
        EXIT WHEN CUR_VAR%NOTFOUND;
        
        INSERT INTO BONUS(ENAME,JOB,SAL,COMM)
        VALUES(R_CUR_EMP.ENAME,R_CUR_EMP.JOB,R_CUR_EMP.SAL,R_CUR_EMP.COMM);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('TOTAL ' ||TO_CHAR(CUR_VAR%ROWCOUNT)|| ' rows processed');
    CLOSE CUR_VAR;
    COMMIT;
END;
/


SELECT * FROM BONUS;
SELECT * FROM EMP;